import type { NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { PostDetailContainer } from "../../components/postDetail/Container";
import { Post } from "../../types/Post";

const PostDetail: NextPage = () => {
  return (
    <>
      <Head>
        <title>delight | 감귤마켓</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="sr-only">게시글 상세 페이지</h1>
      <PostDetailContainer />
    </>
  );
};

export default PostDetail;