import type { NextPage } from "next";
import Head from "next/head";
import { ProductContainer } from "../../components/product/Container";

const Product: NextPage = () => {
  
  return (
    <section>
      <Head>
        <title>상품 등록｜감귤마켓</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="sr-only">상품 등록 페이지</h1>
      <ProductContainer />
    </section>
  );
};

export default Product;