import type { NextPage } from "next";
import Head from "next/head";
import { Header } from "../components/follower/Header";

const Follower: NextPage = () => {
  return (
    <div id="app">
      <Head>
        <title>Follower</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
    </div>
  );
};

export default Follower;
