import type { NextPage } from "next";
import Head from "next/head";
import { LoginMain } from "../components/login/Main";

const HomePage: NextPage = () => {
  return (
    <div>
      <Head>
        <title>감귤마켓</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="sr-only">Home</h1>
      <LoginMain />
    </div>
  );
};

export default HomePage;
