// import type { NextPage } from "next";
// import Head from "next/head";
// import { LoginMain } from "../components/login/Main";

// const HomePage: NextPage = () => {
//   return (
//     <div>
//       <Head>
//         <title>감귤마켓</title>
//         <meta name="description" content="Generated by create next app" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>
//       <h1 className="sr-only">Home</h1>
//       <LoginMain />
//     </div>
//   );
// };

// export default HomePage;

import { NextPage } from "next";
import { useSession, signIn, signOut } from "next-auth/react";

const HomePage: NextPage = () => {
  const { data: session } = useSession();

  if (session) {
    return (
      <>
        {/* Signed in as {session.user.email} <br /> */}
        <button onClick={() => signOut()}>Sign out</button>
      </>
    );
  }
  return (
    <>
      Not signed in <br />
      <button onClick={() => signIn()}>Sign in</button>
    </>
  );
};

export default HomePage;
