import type { NextPage } from "next";
import Head from "next/head";
import { LoginPage } from "../components/login/Email";

const Login: NextPage = () => {
  return (
    <section>
      <Head>
        <title>로그인｜감귤마켓</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="sr-only">로그인 페이지</h1>
      <LoginPage />
    </section>
  );
};

export default Login;