import type { NextPage } from "next";
import Head from "next/head";
import { Header } from "../components/research/Header";
import { Main } from "../components/research/Main";
import { Footer } from "../components/research/Footer";
import { useEffect, useState } from "react";
import axios from "axios";
import { useSession } from "next-auth/react";
import { API_ENDPOINT } from "../constants";

const Research: NextPage = () => {
  const { data: session } = useSession();
  const token = session?.user?.name;

  const [researchValue, setResearchValue] = useState("");
  const [researchCards, setResearchCards] = useState([]);

  const Cards = async () => {
    const res = await axios.get(
      `${API_ENDPOINT}user/searchuser/?keyword=${researchValue}`,
      {
        headers: {
          Authorization: `Bearer ${token}`,
          "Content-type": "application/json",
        },
      }
    );
    if (res.data.length > 0) setResearchCards(res.data);
  };

  useEffect(() => {
    Cards();
  }, [researchValue]);

  return (
    <div id="app">
      <Head>
        <title>Research</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="sr-only">감귤마켓 홈화면과 피드</h1>
      <Header setResearchValue={setResearchValue} />
      <Main researchCards={researchCards} />
      <Footer />
    </div>
  );
};

export default Research;
