import type { NextPage } from "next";
import Head from "next/head";
import { SignUpPage } from "../components/signUp";

const SingUp: NextPage = () => {
  return (
    <section>
      <Head>
        <title>회원가입｜감귤마켓</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="sr-only">회원가입</h1>
      <SignUpPage />
    </section>
  );
};

export default SingUp;