import type { NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import { SignUpPage } from "../components/SignUp";
import { SignUpProfile } from "../components/SignUpProfile";

const SingUp: NextPage = () => {
  const [signUp, setSignUp] = useState(true);

  return (
    <section>
      <Head>
        <title>회원가입｜감귤마켓</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="sr-only">회원가입</h1>
      {signUp ? (
        <SignUpPage signUp={signUp} setSignUp={setSignUp} />
      ) : (
        <SignUpProfile />
      )}
    </section>
  );
};

export default SingUp;
