import type { NextPage } from "next";
import Head from "next/head";
import { Header } from "../../../components/following/Header";
import { Main } from "../../../components/following/Main";
import { Footer } from "../../../components/following/Footer";
const Following: NextPage = () => {
  return (
    <div id="app">
      <Head>
        <title>Follower</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Main />
      <Footer />
    </div>
  );
};

export default Following;
