import type { NextPage } from "next";
import Head from "next/head";

const Following: NextPage = () => {
  return (
    <div id="app">
      <Head>
        <title>Follower</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  );
};

export default Following;
