import type { NextPage } from "next";
import Head from "next/head";
import styled from "@emotion/styled";
import { Developer } from "../../components/developer/Developer";
import { Footer } from "../../components/developer/Footer";

const DeveloperPage: NextPage = () => {
  return (
    <Container>
      <Head>
        <title>채팅</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="sr-only">개발자</h1>
      <Developer />
      <Footer />
    </Container>
  );
};

const Container = styled.section`
  display: flex;
  justify-content: center;
  &::before {
    content: "";
    position: absolute;
    z-index: -1;
    width: 100%;
    height: 100vh;
    opacity: 0.7;
    background-image: url("https://cdn.pixabay.com/photo/2021/07/30/04/17/orange-6508617_1280.jpg");
  }
`;

export default DeveloperPage;
