import type { NextPage } from "next";
import Head from "next/head";
import { ChatList } from "../../components/chats/ChatList";

const HomePage: NextPage = () => {
  return (
    <div>
      <Head>
        <title>채팅</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="sr-only">채팅</h1>
      <ChatList />
    </div>
  );
};

export default HomePage;
